name: Auto-compiled builds (Web)

on:
        push:
                branches-ignore: [randomBranchName]
                paths:
                        - '**.hx'
        pull_request:
                branches-ignore: [randomBranchName]
                paths:
                        - '**.hx'

        workflow_dispatch:

jobs:
        buildWeb:
                runs-on: windows-latest

                steps:
                        - uses: actions/checkout@main

                        - uses: krdlab/setup-haxe@master
                          with:
                                  haxe-version: 4.3.6

                        - name: Restore Previous Cache
                          id: cache-build-restore
                          uses: actions/cache/restore@main
                          with:
                                  path: |
                                          .haxelib/
                                          export/debug/html5/haxe/
                                          export/debug/html5/obj/
                                  key: cache-build-html5

                        - name: Installing Libraries
                          run: haxe --interp -cp ./actions/libs-installer -D analyzer-optimize -main Main
                        - name: Create Version Tag
                          run: echo "${{github.run_id}}" > VERSION

                        - name: Compile
                          run: haxelib run lime build html5 -debug -D MOBILE_TESTING

                        - name: Clear Previous Cache
                          uses: actions/github-script@main
                          with:
                                  script: await require('./actions/cache/clear-cache.js')({github, context}, 'cache-build-html5');

                        - name: Save Current Cache
                          uses: actions/cache@main
                          with:
                                  key: cache-build-html5
                                  path: |
                                          .haxelib/
                                          export/debug/html5/haxe/
                                          export/debug/html5/obj/
                                  restore-keys: |
                                          cache-build-html5

                        - name: Upload Artifact
                          uses: actions/upload-artifact@main
                          with:
                                  name: webBuild
                                  path: export/debug/html5/bin
